PaymateMVC/PaymateMVC/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PaymateMVC.Models
{
    public class LoginViewModel
    {
        public int CustomerID { get; set; }

        [Required(ErrorMessage ="Please enter your username")]
        [Display(Name ="Email Address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string UserName { get; set; }

        [Required(ErrorMessage ="Please enter your password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

PaymateMVC/PaymateMVC/Models/RegisterViewModel.cs
using DataAccess.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BusinessObjects;

namespace PaymateMVC.Models
{
    public class RegisterViewModel
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please Enter Your First Name")]
        public string CustomerFirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please Enter Your Last Name")]
        public string CustomerLastName { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter your password")]
        [DataType(DataType.Password)]
        public string CustomerPassword { get; set; }


        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "Enter Your Password Again")]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("CustomerPassword", ErrorMessage = "Passwords Does Not Match")]
        public string ConfirmPassword { get; set; }


        [Display(Name = "Card Number")]
        [Required(ErrorMessage = "Please enter your Card Number")]
        [DataType(DataType.CreditCard)]
        public long? CustomerCardNo { get; set; }

        [Display(Name ="Email Address")]
        [Required(ErrorMessage ="Please Enter Your Email")]
        [EmailAddress(ErrorMessage ="Invalid Email Address")]
        public string CustomerEmailAddress { get; set; }


        public IEnumerable<Gender> Gender { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Please Select Your Gender")]
        public int GenderID { get; set; }



        public CustomerBO Mapping (RegisterViewModel registerViewModel)
        {
            Mapper.Initialize(c => c.CreateMap<RegisterViewModel, CustomerBO>());
            var customerBo = Mapper.Map<CustomerBO>(registerViewModel);
            customerBo.CreatedOn = DateTime.Now;
            return customerBo;
        }

    }
}

PaymateMVC/PaymateMVC/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaymateMVC.Controllers
{
    public class DashBoardController : Controller
    {
        // GET: DashBoard
        public ActionResult MainMenu()
        {
            return Content("DashBoard running");
        }
    }
}

PaymateMVC/PaymateMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaymateMVC.Controllers
{
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PaymateMVC/PaymateMVC/Controllers/SecurityController.cs
using AutoMapper;
using BusinessObjects;
using PaymateMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UIServices.CustomerServices;
using UIServices.LookupServices;

namespace PaymateMVC.Controllers
{


    public class SecurityController : Controller
    {

        private readonly LoginService _LoginService;
        private readonly GenderLookupService _GenderLookupService;
        private readonly RegisterService _RegisterService;
        //private readonly IMapper _mapper;


        public SecurityController(/*IMapper mapper*/)
        {
            _LoginService = new LoginService();
            _RegisterService = new RegisterService();
            _GenderLookupService = new GenderLookupService();
            //_mapper = mapper;

        }

        //  GET: Security
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel loginViewModel)
        {


            var isLoginValid = _LoginService.Login(loginViewModel.UserName, loginViewModel.Password);
            if (isLoginValid != null)
                return RedirectToAction("MainMenu", "DashBoard");

            TempData["LoginError"] = "LoginError";
            return View("Login", loginViewModel);

        }

        [HttpGet]
        public ActionResult Register()
        {
            var registerViewModel = new RegisterViewModel()
            {
                Gender = _GenderLookupService.GetGender()

            };

            return View(registerViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel registerViewModel)
        {
            var customerBo = registerViewModel.Mapping(registerViewModel);
            _RegisterService.RegisterCustomer(customerBo);
            return Content("oki");
        }
    }



}

PaymateMVC/PaymateMVC/Views/DashBoard/MainMenu.cshtml
@{
    ViewBag.Title = "MainMenu";
    Layout = "~/Views/Shared/_DashBoard.cshtml";
}

<h2>DashBoard main menu running</h2>

PaymateMVC/PaymateMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PaymateMVC/PaymateMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PaymateMVC/PaymateMVC/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Home.cshtml";
}
<header class="masthead">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="brand-heading">PAYmate</h1>
                    <p class="intro-text">
                        A free, responsive, one page Bootstrap theme.
                        <br>Created by Start Bootstrap.
                    </p>
                    <a href="#about" class="btn btn-circle js-scroll-trigger">
                        <i class="fa fa-angle-double-down animated"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- About Section -->
<section id="about" class="content-section text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>About Grayscale</h2>
                <p>
                    Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                    <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.
                </p>
                <p>
                    This theme features stock photos by
                    <a href="http://gratisography.com/">Gratisography</a>
                    
                </p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with SASS and LESS files for easy customization!</p>
            </div>
        </div>
    </div>
</section>
<!-- Download Section -->
<section id="login" class="download-section content-section text-center">
    <div class="container">
        <div class="col-lg-8 mx-auto">
            <h2>Download Grayscale</h2>
            <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
            <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
        </div>
    </div>
</section>
<!-- Contact Section -->
<section id="contact" class="content-section text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>Contact Start Bootstrap</h2>
                <p>
                    Feel free to leave us a comment on the
                    <a href="http://startbootstrap.com/template-overviews/grayscale/">Grayscale template overview page</a>
                    on Start Bootstrap to give some feedback about this theme!
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg">
                            <i class="fa fa-twitter fa-fw"></i>
                            <span class="network-name">Twitter</span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/BlackrockDigital/startbootstrap" class="btn btn-default btn-lg">
                            <i class="fa fa-github fa-fw"></i>
                            <span class="network-name">Github</span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg">
                            <i class="fa fa-google-plus fa-fw"></i>
                            <span class="network-name">Google+</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<footer>
    <div class="container text-center">
        <p>Copyright &copy; PAYmate @DateTime.Now.Year</p>
    </div>
</footer>

PaymateMVC/PaymateMVC/Views/Security/Login.cshtml
@model PaymateMVC.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Login.cshtml";
}
@using (Html.BeginForm("Login", "Security", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container" >
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Login</div>
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(m => m.UserName)
                    @Html.TextBoxFor(m => m.UserName, new { placeholder = "example@example.com", @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.UserName, null, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password, null, new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox"> Remember Password
                        </label>
                    </div>
                </div>
                <input type="submit" name="Login" value="Login" class="btn btn-primary btn-block" />
                <div class="text-center">
                    <a class="d-block small mt-3" href="register.html">Register an Account</a>
                    <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>

}

PaymateMVC/PaymateMVC/Views/Security/Register.cshtml
@model PaymateMVC.Models.RegisterViewModel

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Login.cshtml";
}


<div class="container">
    <div class="card card-register mx-auto mt-5">
        <div class="card-header">Register an Account</div>
        <div class="card-body">

            @using (Html.BeginForm("Register", "Security", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            @Html.LabelFor(x => x.CustomerFirstName)
                            @Html.TextBoxFor(x => x.CustomerFirstName, new { @class = "form-control", placeholder = "Thanzeel" })
                            @Html.ValidationMessageFor(x => x.CustomerFirstName, null, new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(m => m.CustomerLastName)
                            @Html.TextBoxFor(m => m.CustomerLastName, null, new { @class = "form-control", placeholder = "Jalaldeen" })
                            @Html.ValidationMessageFor(m => m.CustomerLastName, null, new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(m => m.GenderID)
                            @Html.DropDownListFor(m => m.GenderID, new SelectList(Model.Gender, "GenderID", "GenderType"), "Select a gender", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.GenderID, null, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.CustomerEmailAddress)
                    @Html.TextBoxFor(x => x.CustomerEmailAddress, null, new { @class = "form-control", placeholder = "thanzeel@example.com" })
                    @Html.ValidationMessageFor(x => x.CustomerEmailAddress, null, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            @Html.LabelFor(x => x.CustomerPassword)
                            @Html.PasswordFor(x => x.CustomerPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.CustomerPassword, null, new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(x => x.ConfirmPassword)
                            @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.ConfirmPassword, null, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.CustomerCardNo)
                    @Html.TextBoxFor(x => x.CustomerCardNo, new { @class = "form-control", placeholder = "0123456789" })
                    @Html.ValidationMessageFor(x => x.CustomerCardNo, null, new { @class = "text-danger" })
                    
                </div>

                <input type="submit" value="Register" class="btn btn-primary btn-block">
            }
            <div class="text-center">
                @Html.ActionLink("Login", "Login", "Security", null, new { @class = "d-block small mt-3" })
                @*<a class="d-block small" href="forgot-password.html">Forgot Password?</a>*@
            </div>
        </div>
    </div>
</div>

PaymateMVC/PaymateMVC/Views/Shared/_DashBoard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

PaymateMVC/PaymateMVC/Views/Shared/_Home.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>
    <title>PAYmate</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">PAYmate</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Login", "Login", "Security", null, new { @class = "nav-link js-scroll-trigger" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Register", "Register", "Security", null, new { @class = "nav-link js-scroll-trigger" })
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PaymateMVC/PaymateMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PaymateMVC/PaymateMVC/Views/Shared/_Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title></title>
    @Styles.Render("~/Login/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/toastr/css")
</head>
<body class="bg-dark" style="">
    @RenderBody()
    @Scripts.Render("~/Login/js")
    @Scripts.Render("~/bundles/jqueryval")
    @if (TempData["LoginError"] != null)
    {
        @Scripts.Render("~/Bundles/toastr")
    }
</body>
</html>